### ISSUE TITLE
 error: implicit declaration of function '_PyGen_Send'

### ISSUE THREAD

**Issue by torkos** [suarezvictor/CflexHDL#3]
Trying to build on macOS, using python 3.10

Get errors like below:

```
clangparser.c:21776:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                  ^
clangparser.c:21776:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
            ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
clangparser.c:21781:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                  ^
clangparser.c:21781:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
            ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
clangparser.c:21865:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            ret = _PyGen_Send((PyGenObject*)yf, NULL);
                  ^
clangparser.c:21865:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
            ret = _PyGen_Send((PyGenObject*)yf, NULL);
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 3 errors generated.
```

Also, tried to regenerate clangparser.c from the makefile to see if that would correct everything, but I believe some files are missing, like:
private/clangparser.py

**Comment by suarezvictor** [comment]
Hi torkos
It seems the fix is to use a Cython version >= 0.29.22, see https://github.com/Toblerity/Fiona/issues/1043#issuecomment-974886050 and https://github.com/cython/cython/issues/3876

Just in case I added a file to support python 3.10 (I use minor version 7, if you use a different one just rename the file, it should be compatible)
You should pull the new version and run make in [cflexparser](https://github.com/suarezvictor/CflexHDL/tree/main/cflexparser) directory

I tested it using Cython version 0.29.32 in Debian 12 "bookworm"

**Comment by torkos** [comment]
Ok, I'll try it tonite.

**Comment by torkos** [comment]
Thank you very much Victor.  With your updates, I got it to work!  I run on an M1 Mac.
With the update, it was still giving me some compile issues on the Mac about unknown
python symbols.  But when I added `--embed` in the python-config call, the compile issues
went away and it compiled.

I tried it with both 3.10.0 and 3.10.8, and it seemed to compile fine.

When running the python code the clang module would crash because it kept trying to dynamically
load the x86_64 clang library.  But I was able to resolve that by using:
`clang.cindex.Config.set_library_path` and `clang.cindex.Config.set_library_file`to point to my local library.

I know tools like these can be finicky, and it can take a while to make the process seamless across various setups.  But I appreciate the effort.  FPGA's are fairly new to me and I'm slowly wrapping my head around it all.  On the other hand, I have been working with c++, graphics, animation, computer vision, physics for a very long time ... so it would be fun if I could test out ideas with a better cadence.

Also, at a higher level I think that understanding your approach to the problem would also come in handy at some point.

In any case, thank you for your help. Time to do some experiments.  In the short term, I'm going to push forwards and try to make it build on orange crab 85f and ulx3s.

**Comment by suarezvictor** [comment]
Good that you have run it!
But I still call to the problematic _PyGen_Send functiion. What did you change to avoid the error at calling it? I want to make sure orher MacOS users won't face the same problem

**Comment by torkos** [comment]
For whatever reason, I couldn't get to work using the dynamic library but when I used --embed the message went away.
It could just be me, Im not sure.  But in the end, the makefile for cflexparser ended up looking like this:

```
PARSER_C=clangparser$(PYVER).c

all: clangparser.so

$(PARSER_C):
	@cython -3  --embed private/clangparser.py -o clangparser.cxx
	$(CC) -fpreprocessed -dD -E -P $(shell python3-config --cflags) clangparser.cxx > $(PARSER_C)
	@rm clangparser.cxx

clangparser.so: $(PARSER_C)
	$(CC) -o clangparser.so -shared $(PARSER_C) -fPIC $(shell python3-config --embed --cflags --ldflags)

clean:
	rm -Rf clangparser.so $(PARSER_C) clangparser.cxx __pycache__ private/__pycache__
```
